# -*- coding: utf-8 -*-
"""exercicio-03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/189L0fqfysW_QL8GADlE_WMFqCoXjQJrI
"""

NIR = 0.5
Red = 0.3
Green = 0.6 

print ("NIR:", NIR)
print ("red:", Red)
print ("Green:", Green)

NDVI = (NIR - Red) / (NIR + Red)

NDWI = (Green - NIR) / (Green + NIR)

print("NDVI:" , NDVI)
print("NDWI:" , NDWI)