# -*- coding: utf-8 -*-
"""exercicio-02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E-xLHIj6oGhQmN662B8Qa2sc6ouiXn0-
"""

5 / 2

7 * 4 + 2

(7 * 4) + 2

7 * (4 + 2)

2 ** 3

2 ** 3 ** 4

5 % 2

6 % 2

7 % 2

8 % 2

5 + 1

5.0 + 1

import math 

5 * math.log10(100) - 8 ** 2

import math

math.pi

import math

math.sin(math.pi / 2 )

import math 

math.cos(math.pi / 4 )