# -*- coding: utf-8 -*-
"""Exercício-03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MpESeCOPslk4Ud3ATo77QwZpXSHLSNKE
"""

numero=int(input('Digite um inteiro: '))

if(numero%2) == 0:
    print("Par")
else:
    print("Ímpar")