# -*- coding: utf-8 -*-
"""exercicio-03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1URz9SY0B2LIGBq2hK94m5l5Kiw5AbvLz
"""

xg = float(input("Insira o valor referente à banda espectral da faixa do verde: "))
xn = float(input("Insira o valor referente à banda espectral da faixa do infravermelho próximo: "))
xr = float(input("Insira o valor referente à banda espectral da faixa do vermelho: "))

###CÁLCULO DO NDWI
ndwi = float(( xg - xn ) / ( xg + xn))
print("O valor de NDWI é: ", ndwi)

###CÁLCULO DO NDVI
ndvi = float(( xn - xr ) / ( xn + xr ))
print("O valor de NDVI é: ", ndvi)