# -*- coding: utf-8 -*-
"""Exercício-07

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1olnZ75x8i_7Rkgx_87EH2LIHCsva61JV
"""

var1 = float( input("Digite um numero: ") )
var2 = float( input("Digite outro numero: ") )

print('Soma:             ', var1,'+',var2,' = ' , var1+var2)
print('Subtração:        ', var1,'-',var2,' = ' , var1-var2)
print('Multiplicação:    ', var1,'*',var2,' = ' , var1*var2)
print('Divisão:          ', var1,'/',var2,' = ' , var1/var2)