# -*- coding: utf-8 -*-
"""exercicio-01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nck5aN3pqfLxLVzNZX8XdwWapIbwATnn
"""

type(1)

type(True)

type(5 / 2)

type(2.5)

type(False)

type(5 + 3j)