# -*- coding: utf-8 -*-
"""Exercício-04

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12DTKzu1Ye0OvJTZODu-y8-3TlOs_6v0v
"""

numero=int(input("Digite um valor: "))
if (numero % 2) == 0:
    print("O valor digitado (",numero,") é divisível por dois")
else:
    print("O valor digitado (",numero,") NÃO é divisível por dois")
if (numero % 3) == 0:
    print("O valor digitado (",numero,") é divisível por três")
else:
    print("O valor digitado (",numero,") NÃO é divisível por três")
if (numero % 2  % 3) == 0:
    print("O valor digitado (",numero,") é divisível por dois ou três")
else:
    print("O valor digitado (",numero,") NÃO é divisível por dois ou três")