# -*- coding: utf-8 -*-
"""Exercício-02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s8SD1kRanZf1Tid95U5e2DyETL8EVy6S
"""

a=float(input('Primeiro lado: '))
b=float(input('Segundo  lado: '))
c=float(input('Terceiro lado: '))

if (a + b < c) or (a + c < b) or (b + c < a):
        print('Nao é um triangulo')
elif (a == b) and (a == c) :
        print('Equilatero')
elif (a==b) or (a==c) or (b==c):
        print('Isósceles')
else:
        print('Escaleno')