# -*- coding: utf-8 -*-
"""exercício-02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svqTZYuax0-PCv7h0C5PofMX-txjN7Vo
"""

#definindo a lista de operações
operacoes = ("+", "-", "*", "/" )

a = float(input("Digite o primeiro número: "))
op = input("Digite a operação (+ - * / ): ")

while op in operacoes:
    b = float(input("Digite o segundo número: "))

    if operacoes.index(op) == 0:
        print(f'{a} {op} {b} = {(a + b):.6f}')
        op = input("Escolha a proxima operação (+ - * / )\nOu pressione ENTER para terminar.")
        a = a + b

    elif operacoes.index(op) == 1:
        print(f'{a} {op} {b} = {(a - b):.6f}')
        op = input("Escolha a proxima operação (+ - * / )\nOu pressione ENTER para terminar.")
        a = a - b

    elif operacoes.index(op) == 2:
        print(f'{a} {op} {b} = {(a * b):.6f}')
        op = input("Escolha a proxima operação (+ - * / )\nOu pressione ENTER para terminar.")
        a = a * b

    elif b == 0:
        print("Inválido. Denominador deve ser diferente de zero.")
        break

    elif operacoes.index(op) == 3:
        print(f'{a} {op} {b} = {(a / b):.6f}')
        op = input("Escolha a proxima operação (+ - * / )\nOu pressione ENTER para terminar.")
        a = a / b
    else:
        print("Operação inválida.")
        break

print("Calculadora finalizada.")