# -*- coding: utf-8 -*-
"""exercicio-02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qI-SbkB65f7XZPwYaeSAdg7h1t7s-ah8
"""

5 / 2
#2.5

7 * 4 + 2
#30

(7 * 4) + 2
#30

7 * (4 + 2)
#42

2 ** 3
#8

2 ** 3 ** 4
#2417851639229258349412352

2 ** -3 ** 4
#4.1359030627651384e-25

5 % 2
#1

6 % 2
#0

7 % 2
#1

8 % 2
#0

5 + 1
#6

5.0 + 1
6.0

5 * math.log10(100) - 8 ** 2
#-54.0

math.pi
#3.141592653589793

math.sin(math.pi / 2 )
#1.0

math.cos(math.pi / 4 )
0.7071067811865476