# -*- coding: utf-8 -*-
"""exercicio-01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10yY9PjWinnijuoaVwECYUMcvRyXHNaIj
"""

type(1)
#int

type(True)
#bool

type(5 / 2)
#float

type(2.5)
#float

type(False)
#bool

type(5 + 3j)
#complex