# -*- coding: utf-8 -*-
"""Exercício-06

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hFfo15NRaTYG-atkrjG34gjf0Kjf6G6J
"""

nota_1 = float(input('Digite a primeira nota: '))
nota_2 = float(input('Digite a segunda nota: '))
media = (nota_1 + nota_2)/2

if media > 0 and media <= 1.0:
    print('Media: %.2f, Conceito: D.' % (media))

elif media > 1.1 and media <= 2.0:
    print('Media: %.2f, Conceito: C-.' % (media))

elif media > 2.1 and media <= 3.0:
    print('Media: %.2f, Conceito: C.' % (media))

elif media > 3.1 and media < 4.0:
    print('Media: %.2f, Conceito: C+.' % (media))

elif media > 4.1 and media <= 5.0:
    print('Media: %.2f, Conceito: B-.' % (media))

elif media > 5.1 and media <= 6.0:
    print('Media: %.2f, Conceito: B.' % (media))

elif media > 6.1 and media < 7.0:
    print('Media: %.2f, Conceito: B+.' % (media))

elif media > 7.1 and media <= 8.0:
    print('Media: %.2f, Conceito: A-.' % (media))

elif media > 8.1 and media <= 9.0:
    print('Media: %.2f, Conceito: A.' % (media))

elif media > 9.1 and media <= 10.0:
    print('Media: %.2f, Conceito: A+.' % (media)) 
else:
    print('Nota inválida, Nota1: %.2f, Nota2: %.2f' % (nota_1, nota_2))