# -*- coding: utf-8 -*-
"""Exercício-01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AdykNDP1NDHceNIPf5w1lgsMNjOgYQk7
"""

n1 = int(input('Primeiro número: '))
n2 = int(input('Segundo número: '))
n3 = int(input('Terceiro número: '))

maior = n1
menor = n1

if maior < n2:
	maior = n2
if maior < n3: 
	 maior = n3
if menor > n2:
	 menor = n2
if menor > n3:
	 menor = n3

print ('Maior:  %d ' %maior)
print ('Menor:  %d ' %menor)